apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: demo123
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo123 
  name: demo123
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: demo123
    weight: 100 
